---
- hosts: mywebserver 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install a webserver
    apt:
       name: apache2
       state: present   

  - name: i want to copy into ansible nodes
    template:
         src: indexfile
         dest: /var/www/html/inex.html     

