---
- hosts: 172.31.37.200 
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: wget
  tasks: 
  - name: i ant to display myvar1
    debug:
       msg: "{{myvar1}}" 
    
  - name: install git
    apt:
      name: "{{myvar1}}"
      state: present

    loop:
     - "{{myvar1}}"
     - "{{myvar2}}"
     - "{{myvar3}}"