---
- hosts: all
  become: yes
  tasks: 
   - name: install webserver
     apt:
       name: apache2
       state: present
        
   - name: restart webserver
     service:
        name: apache2
        state: started       